---

- name: Restart rabbitmq-server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted

- name: Start rabbitmq-server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started

- name: Stop rabbitmq-server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: stopped
